tact-app/web

- .github/dependabot.yml
- .github/settings.yml
- .github/stale.yml
Configure
- repository settings
- dependabot
- stalebot
> ci/cd: define common inventory

- components/pages/Goals/modals/GoalCreationModal/components/GoalCreationSelectTemplate.tsx
- components/pages/Inbox/components/FocusConfiguration/store.ts
- components/pages/Inbox/components/FocusConfiguration/view.tsx
- components/pages/Inbox/components/GoalsSelection/store.ts
- components/pages/Inbox/components/GoalsSelection/view.tsx
- components/pages/Inbox/components/TaskList/index.tsx
- components/pages/Inbox/modals/store.ts
- components/pages/Inbox/store.ts
- components/shared/AutoFitInput/index.tsx
- components/shared/BlockNoteEditor/extensions/MetricExtension/command.tsx
- components/shared/BlockNoteEditor/extensions/MetricExtension/index.ts
- components/shared/BlockNoteEditor/extensions/MetricExtension/store.ts
- components/shared/BlockNoteEditor/extensions/MetricExtension/view.tsx
- helpers/inputChangeWrapper.ts
Also fix several UX problems on the todo list page.
> implement metric for goals editor

- .github/dependabot.yml
- Taskfile
- tools/package-lock.json
> ci/cd: configure dependabot for tools and github actions

- components/pages/Inbox/components/FocusConfiguration/view.tsx
- components/pages/Inbox/components/GoalsSelection/view.tsx
- components/pages/Inbox/components/TaskCreator/view.tsx
- components/pages/Inbox/components/TaskList/index.tsx
- components/pages/Inbox/components/TaskQuickEditor/TaskQuickEditorMenu.tsx
- components/pages/Inbox/components/TaskQuickEditor/store.ts
- components/pages/Inbox/components/TaskQuickEditor/suggestionsMenuStore.ts
- components/pages/Inbox/modals/TaskGoalAssignModal/view.tsx
- components/pages/Inbox/store.ts
- components/shared/DraggableList/index.tsx
- components/shared/DraggableList/view.tsx
- middleware.ts
- fix goals list checkboxes
- fix task list dnd button
- fix task deletion behavior
- fix tags creation
- fix index page
> Various bug fixes

- components/pages/Today/components/Calendar/ResizableBlocks/store/navigation.ts
Fix unable to delete all time blocks, remove moveFocus function from removeItem function.
> tact-150: remove move focus function from remove item function

- components/pages/Spaces/components/SpacesInboxItem/view.tsx
[TACT-168/](https://linear.app/octolab/issue/TACT-168/weird-looking-scroll)
Fixed X/Y scroll in space inbox item component.
> TACT-168: Fixed scroll in space inbox item

- components/pages/Spaces/components/SpacesInbox/store.ts
- components/pages/Spaces/components/SpacesInbox/view.tsx
- components/shared/Search/index.tsx
[TACT-166](https://linear.app/octolab/issue/TACT-166/inbox-search-isnt-working)
Inbox search didn't work. As part of this request, I created a separate component for the search field and filtered elements in the Inbox.
> TACT-166: Added search field and Inbox elements filtering

- components/shared/Task/view.tsx
[TACT-172](https://linear.app/octolab/issue/TACT-172/missing-scroll-when-writing-long-text)
Fixed scrolling in the editor in the task component.
> TACT-172: Fixed scroll for editor

- components/pages/Today/components/Calendar/CalendarTableHeader.tsx
- components/pages/Today/components/Calendar/store.ts
[TACT-148](https://linear.app/octolab/issue/TACT-148/incorrect-display-of-dates)
Fixed display of dates for the week and paging by days in the calendar
> TACT-148: Fixed incorrect display of dates for week

- components/shared/TasksList/components/TaskItemMenu/index.tsx
[TACT-108](https://linear.app/octolab/issue/TACT-108/strange-behavior-after-unfocusing-task)
Added task focus when user opens dropdown menu
> TACT-108: Strange behavior after unfocusing task

- components/shared/TaskCreator/view.tsx
[TACT-167](https://linear.app/octolab/issue/TACT-167/overlay-windows-in-inbox)
Fixed input overlaying and added collapse to show the help bar on small screens
> TACT-167: Fixed overlay and help panel for small screens

- components/shared/TasksList/components/TaskItem/view.tsx
[TACT-129](https://linear.app/octolab/issue/TACT-129/regress-of-title-overflow-cutting)
Fixed truncation with the addition of an ellipsis in the title of the task
> TACT-129: Regress of title overflow cutting

- components/pages/Today/components/FocusConfiguration/store.ts
- components/pages/Today/components/FocusConfiguration/view.tsx
- components/shared/TasksList/components/TaskItemMenu/index.tsx
- components/shared/TasksList/modals/TaskGoalAssignModal/store.ts
- components/shared/TasksList/modals/TaskGoalAssignModal/view.tsx
- components/shared/TasksList/modals/TaskWontDoModal/store.ts
- components/shared/TasksList/modals/TaskWontDoModal/view.tsx
- removed ref link (fixed closure cbs)
- fixed meta+enter actions for saving
- tact-85: changed context menu hotkeys (added alt key)
> Tact 178 task context menu

- Taskfile
- components/pages/Today/store.ts
- components/shared/TasksList/components/TaskItem/store.ts
- removed resize calendar by focus
- patch taskFile
- fix event ignore
> tact-182: removed resize calendar by focus

- components/pages/Today/components/Calendar/ResizableBlocks/store/navigation.ts
Removed hotkeys handlers that blocked events in modals
> Tact 184 delete modal btns

- components/shared/ResizableGroup/ResizableGroupChild.tsx
> tact-152 fixed overlay while drag-n-droping

- components/shared/TasksList/components/TaskItem/store.ts
- helpers/combinations.ts
To avoid problems with hotkeys, there is a need for a convenient interface for working with them.
Added `checkKeyCombination`, `checkKeyCombinations` helpers.
> tact-185 patched keydown handler

- components/shared/TaskCreator/view.tsx
- components/shared/TaskQuickEditor/TaskQuickEditorTags.tsx
[TACT-24](https://linear.app/octolab/issue/TACT-24/abuse-inline-editor-by-tags)
Fixed hiding tags under the button.
> TACT-24: Abuse inline editor by tags

- components/shared/ResizableGroup/ResizableGroupChild.tsx
- components/shared/TasksList/components/TaskItemMenu/index.tsx
> tact-146 fixed additional menu jumps

- components/shared/TasksList/components/TaskItem/store.ts
- pages/_app.tsx
Сontext menu may not always open.
Fixed unstable opening context menu.
Fixed context menu outline.
> tact-198 fixed unstable opening context menu

- pages/_app.tsx
Remove excess outline
Removed outline.
> tact-198 fixed outline

- components/shared/GoalsSelection/view.tsx
[TACT-95](https://linear.app/octolab/issue/TACT-95/focusing-mode-explodes-with-a-long-titled-goal)
Trimming a string with an ellipsis for the target title.
> TACT-95: Focusing mode explodes with a long-titled goal

- components/shared/Editor/Editor.module.css
- components/shared/Editor/slashCommands.tsx
- components/shared/Editor/store.ts
- components/shared/Editor/view.tsx
- helpers/validators.ts
- package-lock.json
- package.json
[TACT-17](https://linear.app/octolab/issue/TACT-17/extended-formatting-support-by-markdown)
- Added Code, Code Block, Quote, Strike. Highlight and Link
- For Link, a popup for entering the url has been implemented
- Renamed and reordered Bullet List
> TACT-17: Extended formatting support by markdown

- components/shared/DraggableList/store.ts
- helpers/useHotkeysHandler.ts
- package-lock.json
- package.json
fix for react-hotkeys-hook 4.3.3
> tact-202: added ctrl

- components/shared/Editor/extensions/MetricExtension/store.ts
[TACT-65](https://linear.app/octolab/issue/TACT-65/deleting-targets-some-unexpected-behavior)
Fixed target nodes deleting
> TACT-65: Deleting targets, some unexpected behavior

- components/pages/Goals/modals/GoalCreationModal/components/GoalCreationDescription.tsx
- components/pages/Goals/modals/GoalCreationModal/view.tsx
- components/shared/Editor/Editor.module.css
- components/shared/Editor/store.ts
- components/shared/Editor/view.tsx
- components/shared/Task/TaskEditor.tsx
- components/shared/Task/view.tsx
- components/shared/TaskQuickEditor/TaskQuickEditorTags.tsx
[TACT-93](https://linear.app/octolab/issue/TACT-93/activate-editing-mode-by-clicking-on-wide-area)
[TACT-203](https://linear.app/octolab/issue/TACT-203/bad-editor-unfocusing-experience)
Changed the layout and behavior of the editor to activate editing.
> TACT-93 & TACT-203: Activate editing mode by clicking on wide area

- components/shared/TaskQuickEditor/TaskQuickEditorTags.tsx
[TACT-170](https://linear.app/octolab/issue/TACT-170/add-crosses-to-tags)
Added crosses to tags to delete
> TACT-170: Add crosses to tags

- components/pages/Today/store.ts
- components/pages/Today/view.tsx
[TACT-233](https://linear.app/octolab/issue/TACT-233/when-scaling-the-window-the-page-collapses-completely)
Fixed task expanding by resize window
> TACT-233: When scaling the window, the page collapses completely

- components/shared/Task/view.tsx
- components/shared/TaskQuickEditor/TaskQuickEditorMainMenu.tsx
- components/shared/TaskQuickEditor/TaskQuickEditorTags.tsx
- components/shared/TaskQuickEditor/store.ts
[TACT-170](https://linear.app/octolab/issue/TACT-170/add-crosses-to-tags)
Fixes
> TACT-170: Tags saving without editor close

- .github/workflows/cd.docker.yml
- .github/workflows/cd.vercel.yml
- .github/workflows/ci.yml
- Taskfile
- package-lock.json
- package.json
- tools/package-lock.json
- tools/package.json
Remove unnecessary and add missed.
> TACT-255 review dependencies

- components/pages/Today/store.ts
- components/shared/DraggableList/view.tsx
- components/shared/Task/store.ts
- components/shared/TasksList/components/TaskItem/store.ts
- components/shared/TasksList/components/TaskItem/view.tsx
- components/shared/TasksList/components/TaskItemMenu/index.tsx
- components/shared/TasksList/components/TaskListItem/index.tsx
- components/shared/TasksList/store.ts
- components/shared/TasksListWithCreator/store.ts
[TACT-100](https://linear.app/octolab/issue/TACT-100/rework-touch-and-click-experience)
- DnD by row
- Removed task description autofocus
- Editing title by click and double click
- Fixed title coping
> TACT-100: Rework touch and click experience

- components/pages/Today/store.ts
- components/shared/DraggableList/view.tsx
- components/shared/Task/store.ts
- components/shared/TaskQuickEditor/TaskQuickEditorTags.tsx
- components/shared/TaskQuickEditor/store.ts
- components/shared/TasksList/components/TaskItem/store.ts
- components/shared/TasksList/store.ts
- components/shared/TasksListWithCreator/store.ts
Please add a reference to a related issue in the project.
- Availability of quick task editing (updated dnd sensors)
- Fixed floating tags
- Update task when it has been unfocused
> TACT-242: Floating tag and focus on hidden delete button (x)

- components/Layout/components/MenuBar/index.tsx
- components/pages/Spaces/components/SpacesIcons/SpacesSmallIcon.tsx
- components/pages/Spaces/components/SpacesInbox/view.tsx
- components/pages/Spaces/modals/SpaceCreationModal/components/SpaceCreationEmojiSelect.tsx
- components/pages/Spaces/modals/SpaceCreationModal/store.ts
- components/pages/Today/components/Calendar/view.tsx
- components/pages/Today/store.ts
- components/shared/DraggableList/store.ts
- components/shared/SpacesSelection/components/SpaceSelectionListItem.tsx
- components/shared/SpacesSelection/index.tsx
- components/shared/SpacesSelection/store.ts
- components/shared/SpacesSelection/view.tsx
- components/shared/Task/TaskModesMenu.tsx
- components/shared/Task/store.ts
- components/shared/TaskQuickEditor/TaskQuickEditorSpace.tsx
- components/shared/TaskQuickEditor/modals/store.ts
- components/shared/TaskQuickEditor/modes/SpaceModeStore.tsx
- components/shared/TaskQuickEditor/store.ts
- components/shared/TasksList/components/TaskItemMenu/index.tsx
- components/shared/TasksList/modals/TaskSpaceChangeModal/index.tsx
- components/shared/TasksList/modals/TaskSpaceChangeModal/store.ts
- components/shared/TasksList/modals/TaskSpaceChangeModal/view.tsx
- components/shared/TasksList/modals/store.ts
- components/shared/TasksList/store.ts
- components/shared/TasksListWithCreator/store.ts
- stores/RootStore/index.tsx
- fixed Inbox emoji picker styles
- changed Inbox icon
- added space creation in suggestions
- added "Change Space" in task menu
- added root var isModalOpen to disable hotkeys at modals open
> tact-118: updated space suggestions

- components/shared/TaskQuickEditor/store.ts
[TACT-104](https://linear.app/octolab/issue/TACT-104/bad-experience-with-esc-and-task-editing)
Saving a priority/goal/tags when edited
> TACT-104: Bad experience with Esc and task editing

- components/shared/TaskQuickEditor/TaskQuickEditorTags.tsx
- components/shared/TaskQuickEditor/modes/TagModeStore.tsx
- fixed windows overlaying
- removed minWidth from tags popover
- fixed tags selecting in popover by keyboard
- refactor tags store
> tact-257: bugfix tags menu

- components/shared/DraggableList/view.tsx
[TACT-99](https://linear.app/octolab/issue/TACT-99/support-dnd-on-random-place-of-a-task-change-cursor-to-pointer-for)
Removed outline for drag handler
> TACT-99: Fixed outline for drag handler

- components/pages/Spaces/components/SpacesMenu/view.tsx
[TACT-223](https://linear.app/octolab/issue/TACT-223/no-scrolling-option-when-creating-more-than-14-spaces)
Scrollable Spaces
> TACT-223: No scrolling option when creating more than 14 spaces

- components/shared/TaskQuickEditor/TaskQuickEditorTags.tsx
- components/shared/TaskQuickEditor/modes/TagModeStore.tsx
- components/shared/TaskQuickEditor/store.ts
[TACT-216](https://linear.app/octolab/issue/TACT-216/it-isnt-possible-to-remove-one-or-more-tags-from-the-editors-list)
- Deleting a tag in expanded task as one transaction
- Restoring task when user pressed Esc on tag
> TACT-216: It isn't possible to remove one or more tags from the editor's list

- components/pages/Spaces/components/SpacesInboxItem/view.tsx
- components/pages/Today/components/TasksListToday.tsx
- components/pages/Today/components/TasksListWeekly.tsx
- components/shared/DraggableList/view.tsx
- components/shared/TasksList/view.tsx
[TACT-247](https://linear.app/octolab/issue/TACT-247/the-presence-of-sorting-in-the-context-of-the-inbox-tab)
Supported disabling dnd and disabled it in Inbox
> TACT-247: The presence of sorting in the context of the inbox tab

- components/pages/Today/components/FocusConfiguration/store.ts
- components/pages/Today/store.ts
[TACT-40](https://linear.app/octolab/issue/TACT-40/make-editor-context-consistent)
The task closing when it isn't related to any goal
> TACT-40: The task closing when it isn't related to any goal

- components/shared/TaskQuickEditor/store.ts
[TACT-245](https://linear.app/octolab/issue/TACT-245/task-with-an-empty-name-jumps-in-edit-mode)
Restricted the creation of a task with an empty title
> TACT-245: Task with an empty name jumps in edit mode

- components/pages/Today/store.ts
- components/shared/Task/store.ts
- components/shared/TaskQuickEditor/modes/TagModeStore.tsx
- components/shared/TaskQuickEditor/store.ts
- components/shared/TaskQuickEditor/suggestionsMenuStore.ts
- components/shared/TasksListWithCreator/store.ts
> Release fixes

- components/shared/TaskCreator/view.tsx
- components/shared/TaskQuickEditor/TaskQuickEditorMenu.tsx
- components/shared/TaskQuickEditor/TaskQuickEditorTags.tsx
- components/shared/TaskQuickEditor/modes/TagModeStore.tsx
> Release fixes #2

- components/pages/Today/components/ListsBlock.tsx
- components/pages/Today/store.ts
- components/shared/AnimatedBlock/index.tsx
- components/shared/DraggableList/store.ts
- components/shared/DraggableList/view.tsx
- components/shared/MouseMultySelect/MouseMultySelect.tsx
- components/shared/MouseMultySelect/types.ts
- components/shared/TaskQuickEditor/TaskQuickEditorTags.tsx
- components/shared/TasksList/components/TaskItem/view.tsx
- components/shared/TasksList/components/TaskItemMenu/index.tsx
- components/shared/TasksList/store.ts
- components/shared/TasksList/view.tsx
- pages/_app.tsx
> Mouse selection refactoring

- components/shared/AnimatedBlock/index.tsx
- components/shared/TaskCreator/index.tsx
- components/shared/TaskQuickEditor/TaskQuickEditorMenu.tsx
- components/shared/TaskQuickEditor/store.ts
[TACT-105](https://linear.app/tact/issue/TACT-105/improve-experience-while-tag-editing)
[TACT-137](https://linear.app/tact/issue/TACT-137/rework-arrow-experience)
Release fixes #3
> Release fixes #3

- components/shared/MouseMultySelect/MouseMultySelect.tsx
- components/shared/MouseMultySelect/types.ts
fixed bug with cursor offset relative to the frame
> returned portal ref

- components/shared/TasksList/components/TaskItem/store.ts
> fixed tasks selection with Ctrl on Win

- components/pages/Today/components/CalendarBlock.tsx
- components/pages/Today/store.ts
- components/shared/TaskQuickEditor/store.ts
[TACT-105](https://linear.app/tact/issue/TACT-105/improve-experience-while-tag-editing)
[TACT-138](https://linear.app/tact/issue/TACT-138/highlight-actual-context)
Release fixes #4
> Release fixes #4

- components/shared/Editor/store.ts
[TACT-138](https://linear.app/tact/issue/TACT-138/highlight-actual-context)
Release fixes #5
> Release fixes #5

- components/shared/TaskQuickEditor/modals/store.ts
- components/shared/TasksList/modals/store.ts
- package-lock.json
- package.json
-
Reverted mobx-react-lite version
> Reverted mobx-react-lite version

- components/pages/Today/components/FocusConfiguration/view.tsx
- components/shared/ActionMenu/components/ActionMenuContent.tsx
- components/shared/ActionMenu/store.ts
- components/shared/ActionMenu/types.ts
- components/shared/TasksList/components/TaskItemMenu/index.tsx
> Fixed action menu display

- components/shared/TasksList/store.ts
- components/shared/TasksListWithCreator/store.ts
[TACT-336](https://linear.app/tact/issue/TACT-336/goal-setting-rework-shange-task-editor-behaviour)
Fixed task creator closing
> TACT-336: Goal setting rework: Сhange Task Editor behaviour

- components/shared/TaskQuickEditor/TaskQuickEditorInput.tsx
- components/shared/TaskQuickEditor/store.ts
- components/shared/TextareaAutofit/index.tsx
[TACT-390](https://linear.app/tact/issue/TACT-390/fix-broken-builds-with-new-typescript-513-and-typesreact-1828)
> TACT-390: Fix broken builds with new typescript (5.1.3) and @types/react (18.2.8)

- components/Layout/index.tsx
- pages/_app.tsx
- stores/RootStore/index.tsx
[TACT-393](https://linear.app/tact/issue/TACT-393/auth0-integration)
> TACT-393: 404 error for pages
